language: android
jdk: oraclejdk7

branches:
   only:
      - unstable

android:
   components:
      - build-tools-21.1.1
      - android-21
      - sys-img-x86-android-21
env:
   global:
      # install timeout in minutes
      - ADB_INSTALL_TIMEOUT=8

# Create and start the emulator
before_script:
   - android list targets
   - echo no | android create avd --force -n test -t "Google Inc.:Google APIs (x86 System Image):21" --abi default/x86
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell inout keyevent 82 & 

script:
   - android list target
   - ./gradlew connectedAndroidTest -PdisablePreDex
   

    
