language: android
jdk: oraclejdk7
sudo: false

branches:
   only:
      - unstable

android:
   components:
      - build-tools-21.1.1
      - android-21
env:
   global:
      # install timeout in minutes
      - ADB_INSTALL_TIMEOUT=8

# Create and start the emulator
before_script:
   - echo no | android create avd --force -n test -t android-21  --abi armeabi-v7a -c 128M
   - emulator -avd test -no-skin -no-audio -no-window &
   - android-wait-for-emulator
   - adb shell input keyevent 82 &
#Build all projects and run the tests   
script:
   - ./gradlew :libs:SalesforceSDK:connectedAndroidTest
   - ./gradlew :libs:SmartStore:connectedAndroidTest
   - ./gradlew :libs:SmartStore:connectedAndroidTest
   - ./gradlew :hybrid:test:ForcePluginsTest:connectedAndroidTest
   - ./gradlew :native:TemplateApp:connectedAndroidTest
   - ./gradlew :native:SampleApps:RestExplorer:connectedAndroidTest
