aliases:
  - &gradle-cache-key
    gradle-cache-v2-{{ checksum "build.gradle" }}-{{
      checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{
      checksum "libs/SalesforceAnalytics/build.gradle" }}-{{
      checksum "libs/SalesforceSDK/build.gradle" }}-{{
      checksum "libs/SmartStore/build.gradle" }}-{{
      checksum "libs/SmartSync/build.gradle" }}-{{
      checksum "libs/SalesforceHybrid/build.gradle" }}-{{
      checksum "libs/SalesforceReact/build.gradle" }}

  - &restore-gradle-cache
    keys:
      - *gradle-cache-key

  - &restore-node-cache
    keys:
      - node-cache-{{ checksum "package.json" }}

  - &restore-ruby-cache
    keys:
      - ruby-gem-cache-{{ .BuildNum }}
      - ruby-gem-cache-

  - &save-gradle-cache
    key: *gradle-cache-key
    paths:
      - .gradle
      - /home/circleci/.gradle

  - &save-node-cache
    key: node-cache-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &save-ruby-cache
    key: ruby-gem-cache-{{ .BuildNum }}
    paths:
      - /home/circleci/.rubies

  - &setup-env
    name: Setup Environment
    command: |
      sudo npm i npm@latest -g
      sudo npm install -g shelljs@0.8.3
      sudo npm install -g cordova@8.1.2
      cordova telemetry off
      ./install.sh
      gem install bundler
      gem install danger
      gem install danger-junit
      gem install danger-android_lint
      gem install danger-jacoco
      echo $TEST_CREDENTIALS > ./shared/test/test_credentials.json


executors:
  linux:
    working_directory: ~/SalesforceMobileSDK-Android
    docker:
      - image: circleci/android:api-28-node
    environment:
      - TERM: "dumb"
      - GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'



#########################
#                       #
#       Test Jobs       #
#                       #
#########################

version: 2.1
jobs:
  setup:
    executor: linux
    steps:
      - checkout
      - restore_cache: *restore-gradle-cache
      - restore_cache: *restore-node-cache
      - restore_cache: *restore-ruby-cache
      - run: *setup-env
      - run:
          name: Run Android Lint
          command:  ./gradlew lint
          when: always
      - run:
          name: Build for Testing
          command:  |
            ./gradlew libs:SalesforceAnalytics:assembleAndroidTest
            ./gradlew libs:SalesforceSDK:assembleAndroidTest
            ./gradlew native:NativeSampleApps:RestExplorer:assembleAndroidTest
            ./gradlew :native:NativeSampleApps:RestExplorer:assembleDebug
      - run:
          name: Run Danger
          command: |
            if [[ $CIRCLE_BRANCH == *"pull"* ]]; then
                # These env vars are not set properly on rebuilds
                export CIRCLE_PULL_REQUEST="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CIRCLE_PULL_REQUESTS="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CI_PULL_REQUEST="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CI_PULL_REQUESTS="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                # This token is completely harmless as it only has public permission and
                # is owned by a bot who isn't a member of the org.
                DANGER_GITHUB_API_TOKEN="279a29d75427e4178cef""b7b5b2d7646c540f025a" danger --dangerfile=.circleci/Dangerfile_PR.rb --danger_id=PR-Check --verbose
            else
                echo "No need to run Danger."
            fi
      - save_cache: *save-gradle-cache
      - save_cache: *save-node-cache
      - save_cache: *save-ruby-cache
      - persist_to_workspace:
          root: .
          paths:
            - ./**

  run-tests:
    executor: linux
    parameters:
      lib:
        type: string
        default: "SalesforceAnalytics"
      test_apk:
        type: string
        default: "libs/SalesforceAnalytics/build/outputs/apk/androidTest/debug/SalesforceAnalytics-debug-androidTest.apk"
      nightly:
        type: boolean
        default: false
    steps:
      - attach_workspace:
          at: ~/SalesforceMobileSDK-Android
      - run:
          name: Determine Tests to Run
          command: |
            if << parameters.nightly >>; then
                echo -e "\n\nNightly -> Run everything."
            else
                LIBS_TO_TEST=$(ruby .circleci/gitChangedLibs.rb)
                echo -e "export LIBS_TO_TEST=${LIBS_TO_TEST}" >> "${BASH_ENV}"

                # Check if tests should run
                if [[ ${LIBS_TO_TEST} == *"<< parameters.lib >>"* ]]; then
                    echo -e "\n\nLibraries to Test-> ${LIBS_TO_TEST//","/", "}."
                else
                    echo -e "\n\nNo need to test << parameters.lib >> for this PR, stopping execution."
                    circleci step halt
                fi
            fi
      - restore_cache: *restore-gradle-cache
      - restore_cache: *restore-node-cache
      - restore_cache: *restore-ruby-cache
      - run:
          name: Build For Testing
          command: ./gradlew libs:<< parameters.lib >>:assembleAndroidTest
      - run:
          name: Authorize gcloud and set config defaults
          command:  |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project mobile-apps-firebase-test
      - run:
          name: Run << parameters.lib >> Tests
          command: |
            if [[ $CIRCLE_BRANCH == *"pull"* ]]; then
                android_api=27
            else
                # Run API 21 on Mon, 23 on Wed, 25 on Fri
                android_api=$((19 + $(date +"%u")))
            fi

            [[ $android_api < 23 ]] && device="Nexus6" || device="NexusLowRes"

            gcloud firebase test android run \
                --project mobile-apps-firebase-test \
                --type instrumentation \
                --app "native/NativeSampleApps/RestExplorer/build/outputs/apk/debug/RestExplorer-debug.apk" \
                --test << parameters.test_apk >>  \
                --device model=$device,version=$android_api,locale=en,orientation=portrait  \
                --environment-variables coverage=true,coverageFile="/sdcard/coverage.ec"  \
                --directories-to-pull=/sdcard  \
                --results-dir=<< parameters.lib >>-${CIRCLE_BUILD_NUM}  \
                --results-history-name=<< parameters.lib >>  \
                --timeout 10m --no-auto-google-login --no-record-video --no-performance-metrics
          no_output_timeout: 600
          halt_build_on_fail: false
      - run:
          name: Copy test results data
          command: |
            mkdir -p firebase/results
            gsutil -m cp -r -U "`gsutil ls gs://test-lab-w87i9sz6q175u-kwp8ium6js0zw/<< parameters.lib >>-${CIRCLE_BUILD_NUM} | tail -1`*" ./firebase/
            mv firebase/test_result_1.xml firebase/results
          when: always
      - store_artifacts:
            path: firebase/
      - store_test_results:
            path: firebase/results
      - run:
          name: Run Danger
          command: |
            if [[ $CIRCLE_BRANCH == *"pull"* ]]; then
                # These env vars are not set properly on rebuilds
                export CIRCLE_PULL_REQUEST="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CIRCLE_PULL_REQUESTS="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CI_PULL_REQUEST="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"
                export CI_PULL_REQUESTS="https://github.com/forcedotcom/SalesforceMobileSDK-Android/${CIRCLE_BRANCH}"

                if ls libs/<< parameters.lib >>/build/outputs/androidTest-results/connected/*.xml 1> /dev/null 2>&1; then
                     mv libs/<< parameters.lib >>/build/outputs/androidTest-results/connected/*.xml libs/<< parameters.lib >>/build/outputs/androidTest-results/connected/test-results.xml
                fi
                # This token is completely harmless as it only has public permission and
                # is owned by a bot who isn't a member of hte org.
                DANGER_GITHUB_API_TOKEN="279a29d75427e4178cef""b7b5b2d7646c540f025a" danger --dangerfile=.circleci/Dangerfile_Lib.rb --danger_id=<< parameters.lib >> --verbose
            else
                echo "No need to run Danger."
            fi
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash)
          when: always

##########################
#                        #
#      Nightly Jobs      #
#                        #
##########################

  generate-artifacts:
    executor: linux
    steps:
      - checkout
      - restore_cache: *restore-gradle-cache
      - restore_cache: *restore-node-cache
      - run: *setup-env
      - save_cache: *save-node-cache
      - run:
          name: Build Libraries
          command:  |
            ./gradlew :libs:SalesforceAnalytics:assemble
            ./gradlew :libs:SalesforceSDK:assemble
            ./gradlew :libs:SmartStore:assemble
            ./gradlew :libs:SmartSync:assemble
            ./gradlew :libs:SalesforceHybrid:assemble
            ./gradlew :libs:SalesforceReact:assemble
          when: always
      - store_artifacts:
          path: libs/SalesforceAnalytics/build/outputs/aar/
          destination: libraries
      - store_artifacts:
          path: libs/SalesforceSDK/build/outputs/aar/
          destination: libraries
      - store_artifacts:
          path: libs/SmartStore/build/outputs/aar/
          destination: libraries
      - store_artifacts:
          path: libs/SmartSync/build/outputs/aar/
          destination: libraries
      - store_artifacts:
          path: libs/SalesforceHybrid/build/outputs/aar/
          destination: libraries
      - store_artifacts:
          path: libs/SalesforceReact/build/outputs/aar/
          destination: libraries
      - run:
          name: Build Native Sample Apps
          when: always
          command:  |
            ./gradlew :native:NativeSampleApps:AppConfigurator:assemble
            ./gradlew :native:NativeSampleApps:ConfiguredApp:assemble
            ./gradlew :native:NativeSampleApps:RestExplorer:assemble
            ./gradlew :native:NativeSampleApps:SmartSyncExplorer:assemble
      - store_artifacts:
          path: native/NativeSampleApps/AppConfigurator/build/outputs/apk/
          destination: native-apps
      - store_artifacts:
          path: native/NativeSampleApps/ConfiguredApp/build/outputs/apk/
          destination: native-apps
      - store_artifacts:
          path: native/NativeSampleApps/RestExplorer/build/outputs/apk/
          destination: native-apps
      - store_artifacts:
          path: native/NativeSampleApps/SmartSyncExplorer/build/outputs/apk/
          destination: native-apps
      - run:
          name: Build Hybrid Sample Apps
          when: always
          command:  |
            ./gradlew :hybrid:HybridSampleApps:AccountEditor:assemble
            ./gradlew :hybrid:HybridSampleApps:NoteSync:assemble
            ./gradlew :hybrid:HybridSampleApps:SmartSyncExplorerHybrid:assemble
      - store_artifacts:
          path: hybrid/HybridSampleApps/AccountEditor/build/outputs/apk/
          destination: hybrid-apps
      - store_artifacts:
          path: hybrid/HybridSampleApps/NoteSync/build/outputs/apk/
          destination: hybrid-apps
      - store_artifacts:
          path: hybrid/HybridSampleApps/SmartSyncExplorerHybrid/build/outputs/apk/
          destination: hybrid-apps
      - save_cache: *save-gradle-cache


#####################
#                   #
#     Workflows     #
#                   #
#####################

workflows:
  version: 2

  # PRs run on Android API 27
  pr-test:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - /pull.*/
      - run-tests:
          requires:
            - setup
          name: "SalesforceAnalytics"
      - run-tests:
          requires:
            - setup
          name: "SalesforceSDK"
          lib: "SalesforceSDK"
          test_apk: "libs/SalesforceSDK/build/outputs/apk/androidTest/debug/SalesforceSDK-debug-androidTest.apk"
      - run-tests:
          requires:
            - setup
          name: "SmartStore"
          lib: "SmartStore"
          test_apk: "libs/SmartStore/build/outputs/apk/androidTest/debug/SmartStore-debug-androidTest.apk"
      - run-tests:
          requires:
            - setup
          name: "SmartSync"
          lib: "SmartSync"
          test_apk: "libs/SmartSync/build/outputs/apk/androidTest/debug/SmartSync-debug-androidTest.apk"
      - run-tests:
          requires:
            - setup
          name: "SalesforceHybrid"
          lib: "SalesforceHybrid"
          test_apk: "libs/SalesforceHybrid/build/outputs/apk/androidTest/debug/SalesforceHybrid-debug-androidTest.apk"
      - run-tests:
          requires:
            - setup
          name: "RestExplorer"
          lib: "RestExplorer"
          test_apk: "native/NativeSampleApps/RestExplorer/build/outputs/apk/androidTest/debug/RestExplorer-debug-androidTest.apk"
      - run-tests:
          requires:
            - setup
          name: "SalesforceReact"
          lib: "SalesforceReact"
          test_apk: "libs/SalesforceReact/build/outputs/apk/androidTest/debug/SalesforceReact-debug-androidTest.apk"


  # Cron are on a timezone 8 hours ahead of PST
  # Nightly run is set for ~10PM
  # Monday    - API 21
  # Wednesday - API 23
  # Friday    - API 25
  nightly-test:
     triggers:
       - schedule:
           cron: "00 6 * * 2,4,6"
           filters:
             branches:
               only:
                 - dev
     jobs:
        - generate-artifacts
        - setup
        - run-tests:
            requires:
              - setup
            name: "SalesforceAnalytics"
        - run-tests:
            requires:
              - setup
            name: "SalesforceSDK"
            lib: "SalesforceSDK"
            test_apk: "libs/SalesforceSDK/build/outputs/apk/androidTest/debug/SalesforceSDK-debug-androidTest.apk"
            nightly: true
        - run-tests:
            requires:
              - setup
            name: "SmartStore"
            lib: "SmartStore"
            test_apk: "libs/SmartStore/build/outputs/apk/androidTest/debug/SmartStore-debug-androidTest.apk"
            nightly: true
        - run-tests:
            requires:
              - setup
            name: "SmartSync"
            lib: "SmartSync"
            test_apk: "libs/SmartSync/build/outputs/apk/androidTest/debug/SmartSync-debug-androidTest.apk"
            nightly: true
        - run-tests:
            requires:
              - setup
            name: "SalesforceHybrid"
            lib: "SalesforceHybrid"
            test_apk: "libs/SalesforceHybrid/build/outputs/apk/androidTest/debug/SalesforceHybrid-debug-androidTest.apk"
            nightly: true
        - run-tests:
            requires:
              - setup
            name: "RestExplorer"
            lib: "RestExplorer"
            test_apk: "native/NativeSampleApps/RestExplorer/build/outputs/apk/androidTest/debug/RestExplorer-debug-androidTest.apk"
            nightly: true
        - run-tests:
            requires:
              - setup
            name: "SalesforceReact"
            lib: "SalesforceReact"
            test_apk: "libs/SalesforceReact/build/outputs/apk/androidTest/debug/SalesforceReact-debug-androidTest.apk"
            nightly: true